### PR TITLE
Committing of VampireProgram folder with 2 files

### PR DESCRIPTION
**Pull request by Justobioma**
I added a folder called VamperProgram which contains a single Python program I used to demonstrate an if-else statement.
I also added a README.md file.

### CODE REVIEW

**Comment by phuocding** [comment]
I can see you input in program, please update!

**Comment by Justobioma** [comment]
can or can't? 
I added a folder with a Python file and README file.
Please advise what I med to do further..

**Comment by phuocding** [comment]
> can or can't?
> I added a folder with a Python file and README file.
> Please advise what I med to do further..

My mistake, I can't see input output this program. It's quite basic

**Comment by Justobioma** [comment]
I am sorry. I don't understand. Kindly put me through

**Comment by phuocding** [comment]
> I am sorry. I don't understand. Kindly put me through

image
Just here, so no input so how to run that? For example, show input for ask one question for answer

**Comment by Justobioma** [comment]
Thanks. Understood now. It was an omission.
Corrected now and will update shortly

**Pull request merged**
